---
title: "e12_ko"
author: "Melanie Smith"
date: "2026-02-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls(all.names = TRUE)) # will clear all objects includuing hidden objects
gc() # free up memory and report the memory usage
options(max.print = .Machine$integer.max,
        scipen = 999,
        stringsAsFactors = FALSE,
        dplyr.summarise.inform = FALSE) # Print everything without truncation, avoid scientific notation, keep strings as characters, silence dplyr’s “grouped output” informational messages
set.seed(42) # set seed for reproducibility
```

# Load Libraries

```{r}
# Core tidyverse
library(tidyverse)
library(tibble)
library(dplyr)
library(tidyr)

# Single Cell
library(Seurat) # Seurat (relies on dplyr/tidyr, so load after tidyverse)

# Plotting
library(patchwork)
```

# Set project directories

```{r}
project_repo_dir <- "/home/melanie-smith/workDir/sophieWiszniak/20251104_sophieWiszniak_ncc_pa"
out_dir <- file.path(project_repo_dir, "outDir", "09-rna_velocity")

# Create directory if it doesn't exist
if (!dir.exists(out_dir)) {
  dir.create(out_dir,
             recursive = TRUE)
}

```
# User defined functions

```{r}
# Helper function (put this at the top of your script)
save_if <- function(plot_object, filename, width, height, ...) {
  if (save_plots) {
    ggsave(plot = plot_object,
           filename = filename,
           width = width,
           height = height,
           dpi = 300)
  }
}
# change to TRUE to save plots
save_plots <- TRUE
```

# Load required Seurat object

```{r}
e12_ko <- readRDS(file.path(out_dir, "e12_ko.rds"))

stopifnot(inherits(e12_ko, "Seurat"))

Idents(e12_ko) <- "seurat_clusters"
Idents(e12_ko) <- factor(Idents(e12_ko))
DefaultAssay(e12_ko) <- "RNA"

# Save the existing Seurat clusters
e12_ko$full_dataset_clusters <- e12_ko$seurat_clusters

```

## Set up the cell-type colours

```{r}
celltype_cols <- c("Myocardium" = "#E41A1C",
                   "VSMC" = "#377EB8", 
                   "Epicardium" = "#4DAF4A",
                   "Mesenchyme" = "#984EA3", 
                   "Endocardium" = "#FF7F00",
                   "Other/Unknown" = "grey70")

epicardial_genes <- c("Wt1", "Upk3b", "Apela", "Upk1b", "Aldh1a2")

endocardial_genes <- c("Ecscr", "Cdh5", "Tie1", "Rasip1", "Plxnd1")
```


# Re-embed Normalise, find variable features, scale, PCA, UMAP, cluster and visualise
## e12_ko

```{r}
# quick dimplot using the existing clusters
DimPlot(e12_ko,
        group.by = "seurat_clusters")

n_dims = 30
# Re-computation of graph-based clustering and UMAP on the cleaned dataset
re_embed_e12_ko <- FindVariableFeatures(e12_ko,
                                        selection.method = "vst", 
                                        nfeatures = 3000,
                                        verbose = FALSE) %>%
  ScaleData(features = rownames(e12_ko),
            verbose = FALSE) %>%
  RunPCA(verbose = FALSE) %>%
  FindNeighbors(dims = 1:n_dims,
                verbose = FALSE) %>%
  RunUMAP(dims = 1:n_dims,
          verbose = FALSE)

# plot the umap with old cluster numbers and colours
umap_oldCluster <- DimPlot(re_embed_e12_ko,
        reduction = "umap",
        group.by = "full_dataset_clusters",
        label = TRUE,
        label.size = 6
        ) +
  labs(
    title = "e12_ko - new embedding (old clusters)",
    caption = "e12_ko"
  ) +
  NoLegend()

save_if(umap_oldCluster,
        filename = file.path(out_dir, "09-umap.re_embed_e12_ko.old_clusters.png"),
        width = 8,
        height = 8)

# plot the umap with new celltypes
umap_newCelltype <- DimPlot(re_embed_e12_ko,
        reduction = "umap",
        group.by = "new_celltypes",
        label = TRUE,
        label.size = 6
        ) +
  labs(
    title = "e12_ko - new embedding (new celltypes)",
    caption = "e12_ko"
  ) +
    scale_color_manual(values = celltype_cols) +
  NoLegend()
save_if(umap_newCelltype,
           filename = file.path(out_dir, "09-umap.re_embed_e12_ko.new_celltypes.png"),
           width = 8,
           height = 8)

endocardial_markers <- FeaturePlot(
  object = re_embed_e12_ko,
  features = c("Ecscr", "Cdh5"),
  ncol = 1,                      # side-by-side panels
  order = TRUE                   # high-expression cells on top
  ) &
  scale_colour_gradientn(
    colours = rev(RColorBrewer::brewer.pal(11, "Spectral")),
    name = "Expression"
  ) &
  plot_annotation(
    title = "e12_ko Endocardial lineage markers",
    caption = "e12_ko"
  ) &
  theme_bw(base_size = 14) &
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5)
  )
endocardial_markers
save_if(endocardial_markers, 
       filename = file.path(out_dir, "09-umap.re_embed_e12_ko.endocardial_genes.png"),
       width = 16,
       height = 8)

epicardial_markers <- FeaturePlot(
  object = re_embed_e12_ko,
  features = c("Wt1", "Upk3b"),
  ncol = 1,                      # side-by-side panels
  order = TRUE                   # high-expression cells on top
  ) &
  scale_colour_gradientn(
    colours = rev(RColorBrewer::brewer.pal(11, "Spectral")),
    name = "Expression"
  ) &
  plot_annotation(
    title = "e12_ko Epicardial lineage markers",
    caption = "e12_ko"
  ) &
  theme_bw(base_size = 14) &
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5)
  )
epicardial_markers
save_if(epicardial_markers, 
       filename = file.path(out_dir, "09-umap.re_embed_e12_ko.epicardial_genes.png"),
       width = 16,
       height = 8)

gfp_e12_ko <- FeaturePlot(
  object = re_embed_e12_ko,
  features = c("pEGFP-1"),
  ncol = 1,                      # side-by-side panels
  order = TRUE                   # high-expression cells on top
) &
  scale_colour_gradientn(
    colours = rev(RColorBrewer::brewer.pal(11, "Spectral")),
    name = "Expression"
  ) &
  plot_annotation(
    title = "e12_ko pEGFP-1 Reporter",
    caption = "e12_ko"
  ) &
  theme_bw(base_size = 14) &
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5)
  )
save_if(gfp_e12_ko, 
       filename = file.path(out_dir, "09-umap.re_embed_gfp_e12_ko.png"),
       width = 8,
       height = 8)

cellCycle_e12_ko <- FeaturePlot(
  object = re_embed_e12_ko,
  features = c("G2M.Score", "S.Score"),
  ncol = 1,                      # vertical panels
  order = TRUE                   # high-expression cells on top
) &
  scale_colour_gradientn(
    colours = rev(RColorBrewer::brewer.pal(11, "Spectral")),
    name = "Expression"
  ) &
  plot_annotation(
    title = "e12_ko Cell Cycle",
    caption = "e12_ko"
  ) &
  theme_bw(base_size = 14) &
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5)
  )
save_if(cellCycle_e12_ko, 
       filename = file.path(out_dir, "09-umap.re_embed_cellCycle_e12_ko.png"),
       width = 8,
       height = 8)

# let's save here and reload in a new session
write_rds(x = re_embed_e12_ko,
          file = file.path(out_dir, "re_embed_e12_ko.rds"))

```