---
title: "06-cellType_filter"
author: "Melanie Smith"
date: "2026-01-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Clean-up environment

```{r}
rm(list = ls(all.names = TRUE)) # will clear all objects includuing hidden objects
gc() # free up memory and report the memory usage
options(max.print = .Machine$integer.max,
        scipen = 999,
        stringsAsFactors = FALSE,
        dplyr.summarise.inform = FALSE) # Print everything without truncation, avoid scientific notation, keep strings as characters, silence dplyr’s “grouped output” informational messages
set.seed(42) # set seed for reproducibility
```

# Load Libraries

```{r}
# Core tidyverse
library(tidyverse)
library(tibble)
library(dplyr)
library(tidyr)

# Single Cell
library(Seurat) # Seurat (relies on dplyr/tidyr, so load after tidyverse)

library(SingleCellExperiment)
library(biomaRt)
library(scuttle)

# additional plotting functions
library(patchwork)
library(pheatmap)
```

# User defined functions

```{r}
# Helper function (put this at the top of your script)
save_if <- function(plot_object, filename, width, height, ...) {
  if (save_plots) {
    ggsave(plot = plot_object,
           filename = filename,
           width = width,
           height = height,
           dpi = 300)
  }
}
# change to TRUE to save plots
save_plots <- TRUE

```

# Set project directories and file paths

```{r}
project_name <- "20251104_sophieWiszniak_ncc_pa"

base_repo_dir <- "/home/melanie-smith/workDir/sophieWiszniak"
project_repo_dir <- file.path(base_repo_dir, project_name)
data_base_dir <- file.path(project_repo_dir, "rawData")
out_dir <- file.path(project_repo_dir, "outDir")
downloads <- file.path(project_repo_dir, "downloads")

new_out_dir <- file.path(out_dir, "05-secondary_QC")

```

# Load required objects
- This object has been filtered for doublets, >10% MT genes and low quality clusters have been removed

```{r}
re_embed_no_low.qual <- readRDS(file = file.path(new_out_dir, "re_embed_filtered_no_multi_fail.rds"))
# Save the existing seurat clusters before we filter and re-embed
re_embed_no_low.qual$seurat_clusters_mt_dbl_quality <- re_embed_no_low.qual$seurat_clusters
```

# Remove un-interesting cell types (RBCs, platelets, macrophages) and re-embed

```{r}
# Check starting number of cells
cat("Starting number of cells:", ncol(re_embed_no_low.qual), "\n")
cat("Red Blood Cells:", sum(re_embed_no_low.qual$seurat_clusters %in% c(14, 20)), "\n")
cat("Macrophages:", sum(re_embed_no_low.qual$seurat_clusters == 22), "\n")
cat("Platelets:", sum(re_embed_no_low.qual$seurat_clusters == 24), "\n")

cat("Total uninteresting cells to remove:", sum(re_embed_no_low.qual$seurat_clusters %in% c(14, 20, 22, 24)), "\n\n")

# Subset to remove low-quality clusters
re_embed_intersting_cells <- subset(re_embed_no_low.qual, 
                          subset = seurat_clusters %in% c(14, 20, 22, 24), 
                          invert = TRUE)

cat("Number of interesting cells:", ncol(re_embed_intersting_cells), "\n\n")

```

# Re-embed: Normalise, find variable features, scale, PCA, UMAP, cluster

```{r}
n_dims = 30
clustering_resolution_0.8 = 0.8
# Re-computation of graph-based clustering and UMAP on the cleaned dataset
re_embed_intersting_cells_0.8 <- FindVariableFeatures(re_embed_intersting_cells,
                                        selection.method = "vst", 
                                        nfeatures = 3000,
                                        verbose = FALSE) %>%
  ScaleData(features = rownames(re_embed_no_low.qual),
            verbose = FALSE) %>%
  RunPCA(verbose = FALSE) %>% # Defaults to features = VariableFeatures()), but better not to specify as these are not yet stored in that object
  FindNeighbors(dims = 1:n_dims,
                verbose = FALSE) %>%
  FindClusters(resolution = clustering_resolution_0.8,
               verbose = FALSE) %>%
  RunUMAP(dims = 1:n_dims,
          verbose = FALSE)

# plot the umap with old cluster numbers and colours
umap_oldCluster <- DimPlot(re_embed_intersting_cells,
        reduction = "umap",
        group.by = "seurat_clusters_mt_dbl_quality",
        label = TRUE,
        label.size = 6
        ) +
  labs(
    title = "UMAP - new embedding (old clusters)",
    caption = "Filtered: Interesting cells (old clusters)"
  ) +
  NoLegend()

save_if(umap_oldCluster,
        filename = file.path(out_dir, "06-cluster_marker_genes", "06-umap.re_embed_intersting_cells.old_clusters.png"),
        width = 8,
        height = 8)

# plot the umap with new cluster numbers and colours
umap_newCluster <- DimPlot(re_embed_intersting_cells,
        reduction = "umap",
        group.by = "seurat_clusters",
        label = TRUE,
        label.size = 6
        ) +
  labs(
    title = "UMAP - new embedding (new clusters)",
    caption = "Filtered: Interesting cells (new clusters)"
  ) +
  NoLegend()
save_if(umap_newCluster,
           filename = file.path(out_dir, "06-cluster_marker_genes", "06-umap.re_embed_intersting_cells.new_clusters.png"),
           width = 8,
           height = 8)

# plot the umap with new cluster numbers and colours
umap_sophieCluster <- DimPlot(re_embed_intersting_cells,
        reduction = "umap",
        group.by = "sophie_celltype_clean",
        label = TRUE,
        label.size = 4
        ) +
  labs(
    title = "UMAP - new embedding (Sophie anno)",
    caption = "Filtered: Interesting cells (Sophie Anno)"
  )
save_if(umap_sophieCluster,
           filename = file.path(out_dir, "06-cluster_marker_genes", "06-umap.re_embed_intersting_cells.sophie_anno.png"),
           width = 8,
           height = 8)

# let's save here and reload in a new session
write_rds(x = re_embed_intersting_cells_0.8,
          file = file.path(out_dir, "06-cluster_marker_genes", "re_embed_intersting_cells_0.8.rds"))

```

```{r}
n_dims = 30
clustering_resolution = 0.6
# Re-computation of graph-based clustering and UMAP on the cleaned dataset
re_embed_intersting_cells_0.6 <- FindVariableFeatures(re_embed_intersting_cells,
                                                      selection.method = "vst", 
                                                      nfeatures = 3000,
                                                      verbose = FALSE) %>%
  ScaleData(features = rownames(re_embed_no_low.qual),
            verbose = FALSE) %>%
  RunPCA(verbose = FALSE) %>% # Defaults to features = VariableFeatures()), but better not to specify as these are not yet stored in that object
  FindNeighbors(dims = 1:n_dims,
                verbose = FALSE) %>%
  FindClusters(resolution = clustering_resolution,
               verbose = FALSE) %>%
  RunUMAP(dims = 1:n_dims,
          verbose = FALSE)

# let's save here and reload in a new session
write_rds(x = re_embed_intersting_cells_0.6,
          file = file.path(out_dir, "06-cluster_marker_genes", "re_embed_intersting_cells_0.6.rds"))
```